config/routes.rb
Preeschool::Application.routes.draw do

  resources :invoices
  resources :registrations, only: [:new, :edit, :create, :update]

  mount RailsEmailPreview::Engine, at: 'emails'

  namespace :admin do
    resources :messages
    resources :kids
    resources :families do
      get 'leads', action: :leads, on: :collection
    end
    resources :invoices do
      post 'notice', action: :notice, on: :member
      post 'reminder', action: :reminder, on: :member
      post 'alert', action: :alert, on: :member
      post 'mark_as_payed', action: :mark_as_payed, on: :member
      post 'replace', action: :replace, on: :member
      post 'cancel', action: :cancel, on: :member

      get 'check_payments', action: :check_payments, on: :collection
      post 'check_payments', action: :check_payments, on: :collection
    end
    resources :finances
  end

  comfy_route :gallery_admin, path: '/admin'
  comfy_route :cms_admin, path: '/admin'

  comfy_route :blog_admin, path: '/admin'
  comfy_route :blog, path: '/blogg'

  get '/bankid', to: redirect('bankid:///?redirect=http://forskolan-solsidan.se/admin/invoices?from_bankid=true'), as: :bankid

  comfy_route :cms, path: '/', sitemap: false

end

app/models/family.rb
class Family < ActiveRecord::Base
  has_paper_trail # https://github.com/airblade/paper_trail

  # TODO: helpers for dealing with mother and father separately
  # TODO: Rails 4 strong parameters instead of attr_accessible

  has_many :kids
  has_many :invoices

  accepts_nested_attributes_for :kids, reject_if: :all_blank


  before_validation :capitalize_names, on: [:create, :update]

  #scope :without_kids, -> { includes(:kids).where("kids.id is null") }
  # scope :has_kid, -> { includes(:kids).where("kids.id is not null") }
  scope :non_leads, -> { where('families.is_lead IS NULL OR families.is_lead != true') }
  scope :leads, -> { where(is_lead: true) }

  def capitalize_names
    self.mother_name = self.mother_name&.titleize
    self.father_name = self.father_name&.titleize
  end

  def self.has_nonzero_fee
    select do |family|
      family.has_nonzero_fee?
    end
  end

  def has_nonzero_fee?
    total_fee > 0
  end

  def total_fee
    kids.active.map(&:fee).sum.round
  end

  def emails
    [mother_email, father_email].compact
  end
  def phones
    [mother_phone, father_phone].compact
  end


  # Name parts
  def father_names
    father_name.split(" ") rescue nil
  end
  def mother_names
    mother_name.split(" ") rescue nil
  end

  # Forenames
  def mother_forenames
    mother_names[0...-1].join(" ")
  end
  def father_forenames
    father_names[0...-1].join(" ")
  end

  # Surnames
  def mother_surname
    mother_names[-1] rescue nil
  end
  def father_surname
    father_names[-1] rescue nil
  end

  def names
    [mother_name, father_name].compact
  end

  # Shorten if same surname
  def surnames
    if father_surname == mother_surname
      mother_surname
    else
      [mother_surname, father_surname].compact.join("/")
    end
  end

  def name
    surnames
  end

  def full_name
    names_as_sentence
  end

  def name_with_kids
    "#{kids.active.map(&:forename).to_sentence} #{name}"
  end

  def names_as_sentence
    if father_surname == mother_surname
      [mother_forenames, father_forenames].to_sentence + " " + mother_surname
    else
      names.to_sentence
    end
  rescue
    names.to_sentence
  end

end

app/controllers/admin/families_controller.rb
class Admin::FamiliesController < Comfy::Admin::Cms::BaseController

  # TODO: caching?

  before_action :build_family,  :only => [:new, :create]
  before_action :load_family,   :only => [:show, :edit, :update, :destroy]

  def index
    # TODO: order by youngest kid
    # TODO: exclude "expired" kids (>3 months since end date)
    @families = Family.order('kids.start_date DESC')
      .non_leads
      .includes(:kids).references(:kids)
      .page(params[:page])
  end

  def leads
    # TODO: order by youngest kid
    # TODO: exclude "expired" kids (>3 months since end date)
    @leads = Family.order(:created_at)
      .leads
      .includes(:kids).references(:kids)
      .page(params[:page])
  end

  def show
    render
  end

  def new
    render
  end

  def edit
    @invoice = @family.invoices.includes(family: :kids).references(family: :kids)
      .not_fully_payed.valid.oldest

    @invoices = @family.invoices.includes(family: :kids).references(family: :kids)
      .valid.by_date.limit(12)

    render
  end

  def create
    @family.save!
    flash[:success] = 'Familj skapades'
    redirect_to :action => :edit, :id => @family
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Failed to create Family'
    render :action => :new
  end

  def update
    @family.update_attributes!(family_params)
    flash[:success] = 'Familj uppdaterades'
    redirect_to :action => :edit, :id => @family
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Kunde ej uppdatera familj'
    render :action => :edit
  end

  def destroy
    @family.destroy
    flash[:success] = 'Familj togs bort'
    redirect_to :action => :index
  end

protected

  def build_family
    @family = Family.new(family_params)
  end

  def load_family
    @family = Family
      .includes(:kids, :invoices).references(:kids, :invoices)
      .find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = "Ingen familj med id #{params[:id]} kunde hittas"
    redirect_to :action => :index
  end

  def family_params
    params.fetch(:family, {}).permit(:mother_name, :father_name, :mother_email, :father_email, :mother_phone, :father_phone, :income, :comment, :parent_at_home)
  end
end

app/views/admin/families/_form.html.haml
.row
  .col-sm-6
    .row
      %h4.text-right.text-muted.col-sm-offset-2.col-sm-2 Mamma
    = form.text_field :mother_name, label: "Namn", icon: "user", label_col: "col-sm-4", control_col: "col-sm-8", class: "input-lg"
    = form.text_field :mother_email, label: "Email", icon: "envelope", label_col: "col-sm-4", control_col: "col-sm-8"
    = form.text_field :mother_phone, label: "Telefon", icon: "phone", label_col: "col-sm-4", control_col: "col-sm-6"
  .col-sm-6
    .row
      %h4.text-muted.text-right.col-sm-offset-2.col-sm-2 Pappa
    = form.text_field :father_name, label: "Namn", icon: "user", label_col: "col-sm-4", control_col: "col-sm-8", class: "input-lg"
    = form.text_field :father_email, label: "Email", icon: "envelope", label_col: "col-sm-4", control_col: "col-sm-8"
    = form.text_field :father_phone, label: "Telefon", icon: "phone", label_col: "col-sm-4", control_col: "col-sm-6"

%hr

- if form.object.id?
  .form-group
    %label.control-label.col-sm-2
      - if not @invoice
        Faktura
      - else
        Faktura för
        %br
        #{@invoice.fee_month_human}
    .form-control-static.col-sm-6.text-muted
      - if not @invoice
        Ingen obetald faktura hittades
      - else
        .btn-group
          = link_to invoice_path(@invoice, format: :pdf), class: 'btn btn-primary' do
            %span.glyphicon.glyphicon-qrcode
            Visa

          - preview_label = nil
          - if !@invoice.last_reminded
            - preview_label = :notice
            = notice_link(@invoice)
          - elsif @invoice.not_recently_reminded? && @invoice.overdue?
            - preview_label = :reminder
            = reminder_link(@invoice)

            - if @invoice.long_overdue?
              = link_to alert_admin_invoice_path(@invoice), method: :post, data: { confirm: 'Säker på att du vill signalera internt om fakturan?' }, class: 'btn btn-danger' do
                %span.glyphicon.glyphicon-asterisk
                Signal

          = admin_links(@invoice)

          -# if preview_label
            - preview_label_sv = { notice: 'notis', reminder: 'påminnelse' }[preview_label]
            = link_to rails_email_preview.rep_email_path('fee_mailer_preview-'+preview_label.to_s, invoice_id: @invoice), class: 'btn btn-default' do
              %span.glyphicon.glyphicon-envelope
              Visa #{preview_label_sv}


    %label.control-label.col-sm-2 Total avgift
    .form-control-static.col-sm-2
      %span.label.label-default #{form.object.total_fee} kr / mån

  %hr
  .form-group
    %label.control-label.col-sm-2 Barn
    - if form.object.kids.any?
      .list-group.col-sm-8
        - form.object.kids.each do |kid|
          = link_to edit_admin_kid_path(kid), class: "list-group-item" do
            %h5
              %span.glyphicon.glyphicon-user
              = kid.forename
              %span.label.label-info.first #{kid.age} år
              %span.label.label-default #{kid.fee} kr / mån
              - if kid.active?
                %span.label.label-success Aktiv
              - else
                %span.label.label-default Inaktiv
              - if kid.free_15_hour_week
                %span.label.label-warning{title: 'Har just nu rätt till allmän förskola 15 timmar per vecka'} AFSK

    - else
      .form-control-static.col-sm-10.text-muted Inga inlagda


= form.text_field :income, placeholder: Kid::default_income, append: "SEK", help: "Påverkar avgiften för förskoleplats. Den nuvarande maxtaxan är #{Kid::maximum_income} kr.", control_col: "col-sm-4"
= form.form_group :parent_at_home, control_col: "col-sm-4" do
  = form.check_box :parent_at_home, label: "Föräldralediga", title: 'Någon av föräldrarna är hemma med barn'

%hr

- if form.object.is_lead? && form.object.lead_comments?
  .form-group
    %label.control-label.col-sm-2 Intresseanmälan
    .form-control-static.col-sm-6.text-muted= form.object.lead_comments

= form.text_area :comment, rows: 3

= form.form_group class: 'form-actions' do
  .col-sm-6
    = form.submit class: 'btn btn-lg btn-primary'
  .col-sm-6.text-right
    - if form.object.id?
      .btn-group
        = link_to admin_family_path(form.object), method: :delete, data: { confirm: 'Säker?' }, class: 'btn btn-danger' do
          %span.glyphicon.glyphicon-remove
          Ta bort

app/views/admin/families/_history.haml
-# REMEMBER that this is mirrored in kids/_history.haml

%h3 Historik
- if @family.history.any?
  - @family.history.reverse.each do |version|
    - if version
      %h4= l(version[:updated_at], format: :long) if version[:updated_at]
      =# raw ap(version.except(:updated_at), plain: true)
      .row
        - version.except(:updated_at).each do |attribute, values|
          .col-md-6.history-event
            .well
              %h5= t("activerecord.attributes.family.#{attribute}")
              - if values.is_a?(Array)
                %p
                  - if values[1].is_a?(TrueClass)
                    härmed
                    %strong sant
                  - elsif values[1].is_a?(FalseClass)
                    härmed
                    %strong falskt
                  - else
                    ändrades från
                    %em= values[0] || "(inget)"
                    till
                    %strong= values[1] || "(inget)"
- else
  %p Inga ändringar har gjorts.

app/views/admin/families/_invoices.haml
- if @invoices.any?
  .page-header
    %hr
    %h3
      Fakturor
      %small Visar senaste 12

  %table.table.table-hover.table-bordered
    %tr
      %th Skapad
      %th Månad
      %th Försening
      %th Avgift
      %th Betalat
      %th Inbetalning från
      %th
    - @invoices.each do |invoice|
      %tr{ title: invoice.status_text_paid, style: "background-color: #{('#F3E2DA' if invoice.overpayed?) || ('#E5EED8' if invoice.fully_payed?)}" }
        /%td.main= link_to invoice.fee_month, edit_admin_family_path(family)
        %td= l(invoice.invoice_date, format: :short).capitalize
        %td= l(invoice.fee_month, format: :month).capitalize
        %td= invoice.overdue_duration.presence || invoice.was_overdue_duration.presence
        %td= "#{invoice.amount.round.to_i} kr"
        %td= "#{invoice.payments.sum(:amount).round.to_i} kr"
        %td= invoice.payments.last &.from_name
        %td
          .btn-group.btn-group-sm
            = link_to invoice_path(invoice, format: :pdf), class: 'btn btn-primary' do
              %span.glyphicon.glyphicon-qrcode
              Visa

app/views/admin/families/edit.html.haml
.page-header
  .row
    .col-sm-8
      %h2
        Familjen #{@family.name}
        - if @family.parent_at_home?
          %span.label.label.label-success{title: 'Föräldralediga'} FL
        - if @family.is_lead?
          %span.label.label.label-primary{title: 'Intresseanmälda'} Intresse

    .col-sm-4.text-right
      .btn-group
        = link_to edit_admin_family_path(@family.id+1), class: 'btn btn-default', title: 'Nästa familj' do
          %span.glyphicon.glyphicon-arrow-down
          Nästa
        = link_to edit_admin_family_path(@family.id-1), class: 'btn btn-default', title: 'Förra familj' do
          %span.glyphicon.glyphicon-arrow-up
          Förra


= comfy_form_for [:admin, @family] do |form|
  = render form

= render partial: 'invoices'

= render partial: 'history'

app/views/admin/families/index.html.haml
.page-header
  = link_to new_admin_family_path, class: 'btn btn-lg btn-default pull-right' do
    %span.glyphicon.glyphicon-plus-sign
    Ny familj
  %h1
    Familjer

= paginate @families, theme: 'comfy'

- cache @families do
  %table.table.table-hover.table-bordered
    %tr
      %th.main Familj
      %th Barn
      %th Avgift
      %th
      %th
      %th Inkomst
      %th.narrow
      %th.narrow
      %th.narrow

    - @families.each do |family|
      %tr{class: family.has_nonzero_fee? ? '' : 'inactive'}
        %td.main= link_to family.full_name, edit_admin_family_path(family)
        %td= family.kids.map(&:forename).to_sentence
        %td.nobr= "#{family.total_fee.to_i} kr"
        %td
          - if family.kids.any?(&:free_15_hour_week)
            %span.label.label.label-warning{title: 'Har just nu rätt till allmän förskola 15 timmar per vecka'} AFSK
        %td
          - if family.parent_at_home?
            %span.label.label.label-success{title: 'Föräldralediga'} FL
        %td.text-muted= "#{family.income} kr" if family.income?
        %td
          - if family.emails.any?
            %span.glyphicon.glyphicon-envelope
        %td
          - if family.phones.any?
            %span.glyphicon.glyphicon-phone
        %td
          - if family.comment?
            %span.glyphicon.glyphicon-comment{title: "Kommentar"}


    %tfoot{style:'background-color:#eee'}
      %tr
        %td.main= "#{Family.all.count} st"
        %td= "#{Kid.has_family.active.count} st"
        %td= "#{Family.all.map(&:total_fee).sum.to_i} kr"
        %td
        %td
        %td
        %td
        %td
        %td

= paginate @families, theme: 'comfy'

app/views/admin/families/leads.html.haml
.page-header
  = link_to new_admin_family_path, class: 'btn btn-lg btn-default pull-right' do
    %span.glyphicon.glyphicon-plus-sign
    Ny familj
  %h2= 'Intresseanmälda familjer'

= paginate @leads, theme: 'comfy'

- cache @leads do
  %table.table.table-hover.table-bordered
    %tr
      %th.main Familj
      %th Barn
      %th Kommentarer
      %th
      %th
      %th Inkomst
      %th.narrow
      %th.narrow
      %th.narrow

    - @leads.each do |family|
      %tr
        %td.main= link_to family.full_name, edit_admin_family_path(family)
        %td
          = family.kids.map(&:forename).to_sentence
          = family.kids.map{|kid| "#{kid.age_now} år" }.to_sentence
        %td= family.lead_comments
        %td
          - if family.kids.any?(&:free_15_hour_week)
            %span.label.label.label-warning{title: 'Har just nu rätt till allmän förskola 15 timmar per vecka'} AFSK
        %td
          - if family.parent_at_home?
            %span.label.label.label-success{title: 'Föräldralediga'} FL
        %td.text-muted= "#{family.income} kr" if family.income?
        %td
          - if family.emails.any?
            %span.glyphicon.glyphicon-envelope
        %td
          - if family.phones.any?
            %span.glyphicon.glyphicon-phone
        %td
          - if family.comment?
            %span.glyphicon.glyphicon-comment{title: "Kommentar"}


    %tfoot{style:'background-color:#eee'}
      %tr
        %td.main= "#{Family.leads.count} st"
        %td= "#{Family.leads.map(&:kids).flatten.count} st"
        %td
        %td
        %td
        %td
        %td
        %td

= paginate @leads, theme: 'comfy'

app/views/admin/families/new.html.haml
.page-header
  %h2 Ny familj

= comfy_form_for [:admin, @family] do |form|
  = render form

app/views/admin/families/show.html.haml
.page-header
  %h2 Familj
  
= debug @family