config/routes.rb
Preeschool::Application.routes.draw do

  resources :invoices
  resources :registrations, only: [:new, :edit, :create, :update]

  mount RailsEmailPreview::Engine, at: 'emails'

  namespace :admin do
    resources :messages
    resources :kids
    resources :families do
      get 'leads', action: :leads, on: :collection
    end
    resources :invoices do
      post 'notice', action: :notice, on: :member
      post 'reminder', action: :reminder, on: :member
      post 'alert', action: :alert, on: :member
      post 'mark_as_payed', action: :mark_as_payed, on: :member
      post 'replace', action: :replace, on: :member
      post 'cancel', action: :cancel, on: :member

      get 'check_payments', action: :check_payments, on: :collection
      post 'check_payments', action: :check_payments, on: :collection
    end
    resources :finances
  end

  comfy_route :gallery_admin, path: '/admin'
  comfy_route :cms_admin, path: '/admin'

  comfy_route :blog_admin, path: '/admin'
  comfy_route :blog, path: '/blogg'

  get '/bankid', to: redirect('bankid:///?redirect=http://forskolan-solsidan.se/admin/invoices?from_bankid=true'), as: :bankid

  comfy_route :cms, path: '/', sitemap: false

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  RECENT = 5.days

  belongs_to :family
  has_many :payments

  has_paper_trail # https://github.com/airblade/paper_trail

  validates_presence_of :family, :invoice_date, :amount

  validates_uniqueness_of :fee_month, scope: :family_id, conditions: -> { valid }
  validates_uniqueness_of :invoice_date, scope: :family_id, conditions: -> { valid }

  validates_uniqueness_of :ocr, conditions: -> { valid }

  before_validation :set_invoice_date, on: [:create]
  before_validation :set_due_date, on: [:create, :update]
  before_validation :set_fee_month, on: [:create]
  before_validation :filter_summer_months, on: [:create]
  before_validation :set_amount, on: [:create, :update]
  before_validation :set_ocr, on: [:create, :update]

  ### SCOPES

  scope :by_amount_due, -> { order(amount_due: :desc) }

  scope :by_date, -> { order(invoice_date: :desc) }
  scope :by_date_asc, -> { order(invoice_date: :asc) }

  # Emulating NULLS LAST below, see http://stackoverflow.com/a/33047654/483020
  scope :by_payed_on, -> { order("payed_on IS NULL ASC").order(payed_on: :desc) }
  scope :by_payed_on_asc, -> { order(payed_on: :asc) }

  scope :canceled, -> { where(canceled: true) }
  scope :valid, -> { where('NOT(canceled IS true)') }

  scope :not_fully_payed, -> { where("amount_due > 0") }
  scope :fully_payed, -> { where("amount_due <= 0.0") }

  scope :overdue, lambda { |date = Date.today| not_fully_payed.where("due_date < ?", date) }
  scope :not_overdue, lambda { |date = Date.today| not_fully_payed.where("due_date >= ?", date) }
  scope :was_overdue_days_average, -> { fully_payed.average("payed_on - due_date").to_f }

  scope :recently_reminded, -> { where("last_reminded >= ?", RECENT.ago) }
  scope :not_recently_reminded, -> { where("last_reminded IS NULL OR last_reminded < ?", RECENT.ago) }
  scope :not_reminded, -> { where(last_reminded: nil) }


  def self.newest
    by_date.first
  end
  def self.oldest
    by_date.last
  end

  def self.long_overdue
    overdue(30.days.ago)
  end

  def long_overdue?
    overdue_days >= 30
  end

  def recently_reminded?
    self.last_reminded? && self.last_reminded >= RECENT.ago
  end
  def not_recently_reminded?
    !recently_reminded?
  end

  def status_text
    "Senaste notis/påminnelse: #{last_reminded ? I18n.l(last_reminded, format: :short) : 'aldrig'}
Senaste interna signal: #{last_alert ? I18n.l(last_alert, format: :short) : 'aldrig'}"
  end

  def status_text_paid
    given_on = payments.last&.given_on
    "#{'Kan vara överbetald!

' if overpayed?}Antal inbetalningar: #{payments.count}
Totalt inbetalat: #{payments.sum(:amount).to_i || '-'} kr
Referens: #{payments.last&.reference || '-'}
Inkom: #{given_on && I18n.l(given_on, format: :short) || '-'}
Markerad som betald: #{payed_on && I18n.l(payed_on, format: :short) || '-'}"
  end

  def overdue?
    not_fully_payed? &&
    self.due_date < Date.today
  end

  def overdue_days
    return 0 unless overdue?
    (Date.today - self.due_date).to_i
  end
  def was_overdue_days
    return 0 unless self.payed_on
    (self.payed_on - self.due_date).to_i
  end

  def overdue_duration(days = overdue_days)
    Invoice.overdue_duration(days)
  end
  def self.overdue_duration(days)
    return '' if days.zero?
    days.date_duration
  end

  def was_overdue_duration
    overdue_duration(was_overdue_days)
  end
  def self.was_overdue_duration_average
    avg = was_overdue_days_average
    avg > 0 ? overdue_duration(avg) : '0 dagar'
  end

  def fee_month_human
    I18n.l(fee_month, format: :month).capitalize
  end

  def filter_summer_months
    return false if self.fee_month.month === 7 && [38,53,50].include?(family.id)
  end

  def self.due_duration
    25.days
  end

  ### DEFAULT SETTERS

  def set_invoice_date
    self.invoice_date ||= Date.today
  end

  # Defaults to 1st day of current month
  def set_fee_month
    now = Date.today
    self.fee_month ||= now.change(day: 1)
  end

  def set_due_date
    self.due_date ||= self.invoice_date + self.class.due_duration
  end

  def set_amount
    return false unless family
    self.amount ||= family.total_fee.round
    self.amount_due ||= self.amount
  end

  # More about OCR number validation on http://www.bankgirot.se/tjanster/inbetalningar/bankgiro-inbetalningar/ocr-referenskontroll/
  def set_ocr
    base = family.kids.active.map{|kid| kid.ssn[0,8].to_i }.sum
    serial = base +
      self.invoice_date.to_s.gsub(/\D/, '').to_i +
      self.amount.round +
      [family.mother_name, family.father_name].join.length
    self.ocr ||= "#{serial}#{Luhn.control_digit(serial)}"
  end

  def not_fully_payed?
    self.amount_due > 0
  end

  def fully_payed?
    !not_fully_payed?
  end

  def payed_amount # TODO: Take into account payments..?
    amount - amount_due
  end

  def overpayed?
    return false unless payments.any?
    payments.sum(:amount).round.to_i > self.amount.round.to_i
  end

  ### ACTIONS

  def pay!(money, given_on = Date.today)
    # FIXME: this will raise in Payment.create_from_bundles if an invoice is canceled
    raise 'Kan inte betala makulerad faktura' if self.canceled?
    return unless money
    # Remember that the fee amount might be different:
    if money.is_a?(Numeric)
      still_due = self.amount_due - money
    elsif money === true
      still_due = 0
    end
    update!(
      amount_due: still_due,
      payed_on: given_on
    )
  end

  def cancel!
    update!(canceled: true)
  end

  # TODO: should have different OCR?
  def replace!
    cancel!
    attrs = self.slice(
      :family_id,
      :invoice_date,
      :due_date,
      :fee_month,
      :last_reminded,
      :last_alert
    )
    replacement = Invoice.create!(attrs)
    replacement.pay!(payed_amount.nonzero?)
    # TODO: notify them?
  end

  def notice!
    FeeMailer.notice(self).deliver_now
    update!(last_reminded: Date.today)
  end

  def reminder!
    FeeMailer.reminder(self).deliver_now
    update!(last_reminded: Date.today)
  end

  def alert!
    FeeMailer.alert(self).deliver_now
    update!(last_alert: Date.today)
  end

  ### CLASS ACTIONS / JOBS

  def self.create_for_families(fee_month: nil, retroactive: true)
    now = I18n.l(Time.now, format: :short)
    month = I18n.l(fee_month || Date.today, format: :month)
    puts "INVOICE CREATION started on #{now} for #{month}..."
    Family.has_nonzero_fee.map do |family|
      begin
        print "Creating invoice for family: #{family.id} (#{family.name})"

        if fee_month
          due_date = if retroactive
            fee_month + Invoice.due_duration
          end
          invoice_date = if retroactive
            fee_month
          end
          print " with retroactive due date #{due_date.to_s}"

          family.invoices.create!(
            fee_month: fee_month,
            invoice_date: invoice_date,
            due_date: due_date
          )

        else
          family.invoices.create!
        end

        print " -> Done!"

      rescue => e
        puts "Error creating invoice: #{e}"
      ensure
        print "\n"
      end
    end
  rescue => e
    puts "Error preparing invoices to create: #{e}"
  ensure
    puts "---"
  end

  def self.send_notices_and_reminders
    self.send_notices
    self.send_reminders unless not PaymentCheck.successful_lately?
  end

  def self.for_notices
    not_reminded.where(invoice_date: Date.today - 1).valid.by_date_asc
  end

  def self.send_notices
    now = I18n.l(Time.now, format: :short)
    puts "NOTICES processing started on #{now}..."
    Invoice.for_notices.map do |invoice|
      begin
        print "Checking invoice: #{invoice.id} (#{invoice.family.name}) for #{invoice.fee_month_human}"

        invoice.notice!
        print " -> Notified!"

      rescue => e
        puts "Error while sending notice: #{e}"
      ensure
        print "\n"
      end
    end
  rescue => e
    puts "Error preparing invoices to notify about: #{e}"
  ensure
    puts "---"
  end


  def self.for_reminders
    overdue.not_recently_reminded.valid.by_date_asc
  end

  def self.send_reminders
    now = I18n.l(Time.now, format: :short)
    puts "REMINDERS processing started on #{now}..."
    Invoice.for_reminders.map do |invoice|
      begin
        print "Checking invoice: #{invoice.id} (#{invoice.family.name}) for #{invoice.fee_month_human} #{invoice.last_reminded ? '-- Last notified/reminded ' + I18n.l(invoice.last_reminded, format: :short) : ''}"

        case invoice.overdue_days
        when 7
          invoice.reminder!
          print " -> First reminder sent, 7 days overdue today!"
        when 14
          invoice.reminder!
          print " -> Second reminder sent, 14 days overdue today!"
        when 21
          invoice.alert!
          print " -> First alert triggered, 21 days overdue today!"
        when 42
          invoice.alert!
          print " -> Second alert triggered, 42 days overdue today!"
        when 84
          invoice.alert!
          print " -> Third alert triggered, 84 days overdue today!"
        end

      rescue => e
        puts "Error while sending reminder: #{e}"
      ensure
        print "\n"
      end
    end
  rescue => e
    puts "Error preparing invoices to remind about: #{e}"
  ensure
    puts "---"
  end

end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < Comfy::Admin::Cms::BaseController

  # TODO: caching?

  before_action :load_invoice, only: [
    :notice, :reminder, :alert, :mark_as_payed, :replace, :cancel
  ]

  def index
    @overdue = Invoice.includes(family: :kids).references(family: :kids)
      .overdue
      .valid.by_date_asc.by_amount_due

    @overdue_page = @overdue.page(params[:page])

    @long_overdue = @overdue.long_overdue

    @all_paid_invoices = Invoice.includes(:payments).references(:payments)
      .fully_payed
      .valid.by_payed_on

    @paid_invoices = @all_paid_invoices.limit(12)

    @unmatched_payments = Payment
      .where(invoice: nil).where.not(from: 'Härnösands Kommun')
      .order(given_on: :desc).limit(12)

    @new_invoices = Invoice.includes(family: :kids).references(family: :kids)
      .not_overdue.not_recently_reminded
      .valid.by_date_asc.by_amount_due
  end

  def check_payments
    result = Payment.try_to_fetch_new!
    logger.info result
    flash[:success] = "Hämtade #{result &.count} nya betalningar (under hela detta dygn)."
  rescue => e
    logger.error e.message
    flash[:danger] = "Kunde inte hämta betalningar: #{e}"
  ensure
    # render json: result
    redirect_to action: :index
  end

  def notice
    @invoice.notice!
    flash[:success] = "Skickade notis om faktura #{@invoice.id}"
  rescue => e
    logger.error e.message
    flash[:danger] = "Notis kunde inte skickas: #{e}"
  ensure
    redirect_to action: :index
  end

  def reminder
    @invoice.reminder!
    flash[:success] = "Skickade påminnelse om faktura #{@invoice.id}"
  rescue => e
    logger.error e.message
    flash[:danger] = "Påminnelse kunde inte skickas: #{e}"
  ensure
    redirect_to action: :index
  end

  def alert
    @invoice.alert!
    flash[:success] = "Skickade signal om obetald faktura #{@invoice.id}"
  rescue => e
    logger.error e.message
    flash[:danger] = "Signal kunde inte skickas: #{e}"
  ensure
    redirect_to action: :index
  end

  def mark_as_payed
    @invoice.pay!(true)
    flash[:success] = "Markerade faktura #{@invoice.id} som betald"
  rescue => e
    logger.error e.message
    flash[:danger] = "Faktura kunde inte markeras som betald: #{e}"
  ensure
    redirect_to action: :index
  end

  def replace
    @invoice.replace!
    flash[:success] = "Återskapade faktura #{@invoice.id} utifrån senaste data"
  rescue => e
    logger.error e.message
    flash[:danger] = "Faktura kunde inte ersättas/återskapas: #{e}"
  ensure
    redirect_to action: :index
  end

  def cancel
    @invoice.cancel!
    flash[:success] = "Makulerade faktura #{@invoice.id}"
  rescue => e
    logger.error e.message
    flash[:danger] = "Faktura kunde inte makuleras: #{e}"
  ensure
    redirect_to action: :index
  end

protected

  def load_invoice
    @invoice = Invoice.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Faktura hittades ej'
    redirect_to action: :index
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  def show
    @invoice = Invoice
      .includes(family: :kids).references(family: :kids)
      .find(params[:id])

    #format.html # TODO: use mailer template with link to PDF?
    respond_to do |format|
      format.json { render json: @invoice }
      format.pdf do
        pdf = InvoicePdf.new(@invoice, view_context)
        send_data pdf.render,
          filename: pdf.filename,
          type: "application/pdf",
          disposition: 'inline'
=begin
        if File.exist?(@invoice.file_path)
          send_file @invoice.file_path, :type => "application/pdf", :disposition => 'inline'
        else
          #redirect_to :action => :edit
          flash[:error] = "Faktura har inte genererats."
        end
=end
      end

    end
  end

end

app/views/admin/invoices/_form.html.haml
.row
  .col-sm-6
    .row
      %h4.text-right.text-muted.col-sm-4 Mamma
    .row
      = form.text_field :mother_name, label: "Namn", icon: "user", placeholder: "Åsa Berg", label_col: "col-sm-4", control_col: "col-sm-8", class: "input-lg"
      = form.text_field :mother_email, label: "Email", icon: "envelope", placeholder: "foralder@hemma.se", label_col: "col-sm-4", control_col: "col-sm-8"
      = form.text_field :mother_phone, label: "Telefon", icon: "phone", placeholder: "0703079187", label_col: "col-sm-4", control_col: "col-sm-6"
  .col-sm-6
    .row
      %h4.text-right.text-muted.col-sm-4 Pappa
    .row
      = form.text_field :father_name, label: "Namn", icon: "user", placeholder: "Johan Sten", label_col: "col-sm-4", control_col: "col-sm-8", class: "input-lg"
      = form.text_field :father_email, label: "Email", icon: "envelope", placeholder: "foralder@hemma.se", label_col: "col-sm-4", control_col: "col-sm-8"
      = form.text_field :father_phone, label: "Telefon", icon: "phone", placeholder: "0703079187", label_col: "col-sm-4", control_col: "col-sm-6"

%hr

- if form.object.id?
  .form-group
    %label.control-label.col-sm-2 Faktura
    .form-control-static.col-sm-3.text-muted
      = link_to 'Visa email', rails_email_preview.rep_email_path('fee_mailer_preview-reminder', family_id: form.object.id), class: 'btn btn-primary'
      = link_to 'Visa PDF', invoice_path(1, format: :pdf, family_id: form.object.id), class: 'btn btn-primary'

    %label.control-label.col-sm-2 Total avgift
    .form-control-static.col-sm-4
      %span.label.label.label-primary #{form.object.total_fee.to_i} kr / mån

  .form-group
    %label.control-label.col-sm-2 Barn
    - if form.object.kids.any?
      .list-group.col-sm-8
        - form.object.kids.each do |kid|
          = link_to edit_admin_kid_path(kid), class: "list-group-item" do
            %h5
              %span.glyphicon.glyphicon-user
              = kid.full_name
              %span.label.label.label-info #{kid.age} år
              %span.label.label.label-default #{kid.fee} kr / mån
              - if kid.active?
                %span.label.label.label-success Aktiv
              - else
                %span.label.label.label-default Inaktiv
            =# link_to 'Ta bort', admin_kid_path(kid), :method => :delete, :data => { :confirm => 'Säker?' }, :class => 'badge'
    - else
      .form-control-static.col-sm-10.text-muted Inga inlagda


= form.text_field :income, placeholder: "10000", append: "SEK", help: "Avgör avgift för förskoleplats.", control_col: "col-sm-4"
= form.form_group :parent_at_home, control_col: "col-sm-4" do
  = form.check_box :parent_at_home, label: "Föräldralediga", title: 'Någon av föräldrarna är hemma med barn'

%hr

= form.text_area :comment, rows: 3

= form.form_group :class => 'form-actions' do
  = form.submit :class => 'btn btn-lg btn-primary'

app/views/admin/invoices/edit.html.haml
.page-header
  %h2 Familj

= comfy_form_for [:admin, @family] do |form|
  = render form

app/views/admin/invoices/index.html.haml
.page-header
  .row
    .col-sm-5
      %h2= 'Försenade fakturor'

    .col-sm-7
      .row
        .col-sm-5
          = link_to check_payments_admin_invoices_path, method: :post, data: { confirm: 'Säker på att du vill försöka hitta och matcha BG-inbetalningar?' }, class: 'btn btn-block btn-lg btn-success', title: 'Hitta och matcha BG-inbetalningar' do
            %span.glyphicon.glyphicon-refresh
            Hitta betalningar

        .col-sm-7
          - last = PaymentCheck.successful.last
          - ok = PaymentCheck.successful_lately?
          %ul.list-group
            %li{ class: (ok ? 'list-group-item list-group-item-success' : 'list-group-item list-group-item-danger') }
              %small
                - if ok
                  %span.glyphicon.glyphicon-ok-sign
                Senast lyckade kontroll:
                - if last
                  = l(last.updated_at, format: :short)
                - else
                  aldrig

  .row.statistics
    .col-sm-3
      .well.well-lg
        %h3
          = @all_paid_invoices.was_overdue_duration_average #.round
        genomsnittlig försening
    .col-sm-3
      .well.well-lg
        %h3
          = @overdue.count
          %small st
        sena fakturor
    .col-sm-3
      .well.well-lg
        %h3
          = @long_overdue.count
          %small st
        mer än en månad sena
    .col-sm-3
      .well.well-lg
        %h3
          = @overdue.sum(:amount_due).round
          %small kr
        totalt värde

= paginate @overdue_page, theme: 'comfy'

%table.table.table-hover.table-bordered
  %tr
    %th Månad
    %th Försening
    %th Barn
    %th Avgift
    %th Utestående
    %th
  - @overdue_page.each do |invoice|
    %tr
      /%td.main= link_to invoice.fee_month, edit_admin_family_path(family)
      %td{ title: invoice.status_text }
        = l(invoice.fee_month, format: :month).capitalize
      %td{ title: invoice.status_text }
        = invoice.overdue_duration
      %td.wrap= link_to invoice.family.name_with_kids, edit_admin_family_path(invoice.family), title: invoice.family.full_name
      %td= "#{invoice.amount.round.to_i} kr"
      %td= "#{invoice.amount_due.round.to_i} kr"
      %td
        .btn-group.btn-group-sm
          = link_to invoice_path(invoice, format: :pdf), class: 'btn btn-primary' do
            %span.glyphicon.glyphicon-qrcode
            Visa

          - if !invoice.last_reminded
            = notice_link(invoice)
          - elsif invoice.not_recently_reminded? && invoice.overdue?
            = reminder_link(invoice)

          = admin_links(invoice)


  %tfoot{style:'background-color:#eee'}
    %tr
      %td
      %td
      %td
      %td
      %td= "#{@overdue.sum(:amount_due).round} kr"
      %td

= paginate @overdue_page, theme: 'comfy'


- if @paid_invoices.any?
  .page-header
    %hr
    %h2
      = 'Nyligen fullt betalda fakturor'
      %small Visar senaste 12

  %table.table.table-hover.table-bordered{style:'background-color: #E5EED8'}
    %tr
      %th Månad
      %th Försening
      %th Barn
      %th Inbetalning från
      %th Barn
      %th Avgift
      %th Betalat
      %th
    - @paid_invoices.each do |invoice|
      %tr{ title: invoice.status_text_paid, style: "background-color: #{'#F3E2DA' if invoice.overpayed?}" }
        /%td.main= link_to invoice.fee_month, edit_admin_family_path(family)
        %td= l(invoice.fee_month, format: :month).capitalize
        %td= invoice.was_overdue_duration
        %td.wrap= link_to invoice.family.kids.active.map(&:forename).to_sentence, edit_admin_family_path(invoice.family), title: invoice.family.full_name
        %td= invoice.payments.last &.from_name
        %td= "#{invoice.family.kids.active.count} st"
        %td= "#{invoice.amount.round.to_i} kr"
        %td= "#{invoice.payments.sum(:amount).round.to_i} kr"
        %td
          .btn-group.btn-group-sm
            = link_to invoice_path(invoice, format: :pdf), class: 'btn btn-primary' do
              %span.glyphicon.glyphicon-qrcode
              Visa


- if @unmatched_payments.any?
  .page-header
    %hr
    %h2
      = 'Ej matchade inbetalningar'
      %small Visar senaste 12

  %table.table.table-hover.table-bordered{style:'background-color: #FEF9E0'}
    %tr
      %th Inkom
      %th Summa
      %th Referens
      %th Från
      %th
    - @unmatched_payments.each do |payment|
      %tr
        %td= l(payment.given_on, format: :long).capitalize
        %td= "#{payment.amount} kr"
        %td= payment.reference
        %td= payment.from_name
        %td
          -#.btn-group.btn-group-sm
            = link_to invoice_path(invoice, format: :pdf), class: 'btn btn-primary' do
              %span.glyphicon.glyphicon-qrcode
              Visa

    %tfoot{style:'background-color:#eee'}
      %tr
        %td
        %td= "#{@unmatched_payments.map(&:amount).sum.round} kr"
        %td
        %td


- if @new_invoices.any?
  .page-header
    %hr
    %h2= 'Färska fakturor'

  %table.table.table-hover.table-bordered{style:'background-color: #DAEAF0'}
    %tr
      %th Månad
      %th Familj
      %th Barn
      %th Avgift
      %th Utestående
      %th
    - @new_invoices.each do |invoice|
      %tr
        /%td.main= link_to invoice.fee_month, edit_admin_family_path(family)
        %td= l(invoice.fee_month, format: :month).capitalize
        %td= link_to invoice.family.surnames, edit_admin_family_path(invoice.family)
        %td= "#{invoice.family.kids.active.count} st"
        %td= "#{invoice.amount.round.to_i} kr"
        %td= "#{invoice.amount_due.round.to_i} kr"
        %td
          .btn-group.btn-group-sm
            = link_to invoice_path(invoice, format: :pdf), class: 'btn btn-primary' do
              %span.glyphicon.glyphicon-qrcode
              Visa

            - if !invoice.last_reminded
              = notice_link(invoice)
            - else
              = reminder_link(invoice)

            = link_to mark_as_payed_admin_invoice_path(invoice), method: :post, data: { confirm: 'Säker på att du vill markera denna faktura som betald?' }, class: 'btn btn-success', title: 'Markera denna faktura som betald' do
              %span.glyphicon.glyphicon-ok-circle
              Betald

            = link_to cancel_admin_invoice_path(invoice), method: :post, data: { confirm: 'Säker på att du vill makulera denna faktura?' }, class: 'btn btn-warning', title: 'Makulera denna faktura' do
              %span.glyphicon.glyphicon-trash
              Makulera

            = link_to replace_admin_invoice_path(invoice), method: :post, data: { confirm: 'Säker på att du vill ersätta denna faktura med en som skapats utifrån senaste datan? Ev. delbetalning kommer att återappliceras.' }, class: 'btn btn-default', title: 'Ersätt denna faktura med en som skapats utifrån senaste datan. Finns delbetalning återappliceras den.' do
              %span.glyphicon.glyphicon-repeat
              Ersätt


    %tfoot{style:'background-color:#eee'}
      %tr
        %td
        %td
        %td
        %td
        %td= "#{@new_invoices.map(&:amount_due).sum.round} kr"
        %td



%p.text-muted
  Logga in på
  = link_to 'SendGrid', 'https://app.sendgrid.com/statistics'
  för mer statistik om mail som skickats ut.

app/views/admin/invoices/new.html.haml
.page-header
  %h2 Ny familj

= comfy_form_for [:admin, @family] do |form|
  = render form

app/views/admin/invoices/show.html.haml
.page-header
  %h2 Familj
  
= debug @family