config/routes.rb
Preeschool::Application.routes.draw do

  resources :invoices
  resources :registrations, only: [:new, :edit, :create, :update]

  mount RailsEmailPreview::Engine, at: 'emails'

  namespace :admin do
    resources :messages
    resources :kids
    resources :families do
      get 'leads', action: :leads, on: :collection
    end
    resources :invoices do
      post 'notice', action: :notice, on: :member
      post 'reminder', action: :reminder, on: :member
      post 'alert', action: :alert, on: :member
      post 'mark_as_payed', action: :mark_as_payed, on: :member
      post 'replace', action: :replace, on: :member
      post 'cancel', action: :cancel, on: :member

      get 'check_payments', action: :check_payments, on: :collection
      post 'check_payments', action: :check_payments, on: :collection
    end
    resources :finances
  end

  comfy_route :gallery_admin, path: '/admin'
  comfy_route :cms_admin, path: '/admin'

  comfy_route :blog_admin, path: '/admin'
  comfy_route :blog, path: '/blogg'

  get '/bankid', to: redirect('bankid:///?redirect=http://forskolan-solsidan.se/admin/invoices?from_bankid=true'), as: :bankid

  comfy_route :cms, path: '/', sitemap: false

end

app/views/comfy/admin/cms/partials/_body_before.html.haml
= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Imprima'
= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Merriweather+Sans'

/ Mobile viewport optimized: j.mp/bplateviewport
/ %meta{:name => "viewport", :content => "width=device-width; initial-scale=1.0; maximum-scale=1.0;"}

.row
  .col-sm-7
    %h1.admin-header.first
      %a{href: '/'}
        %span.glyphicon.glyphicon-asterisk
        Förskolan Solsidan
      \ - Administration
  .col-sm-4
    .row
      - if Rails.env.development?
        .col-sm-6.text-right
          %h1.admin-header.second
            %span.text-danger
              %span.glyphicon.glyphicon-alert
              Obs!
            Utvecklingsläge
      .col-sm-6.text-right
        = form_tag(admin_kids_path, method: "get", id: "kids-search-form") do
          = text_field_tag :name, params[:name], placeholder: "Sök barn"

app/views/comfy/admin/cms/partials/_navigation_inner.html.haml
%li
  = active_link_to 'Meddelanden', admin_messages_path
%li
  %a.quick-add-icon{href: new_admin_family_path, title: "Ny familj"}
    %span.glyphicon.glyphicon-plus-sign
  = active_link_to 'Familjer', admin_families_path
%li
  %a.quick-add-icon{href: new_admin_kid_path, title: "Nytt barn"}
    %span.glyphicon.glyphicon-plus-sign
  = active_link_to 'Barn', admin_kids_path
%li
  = active_link_to 'Fakturor', admin_invoices_path
%li
  = active_link_to 'Finanser', admin_finances_path
%li= active_link_to 'Intresse', leads_admin_families_path