config/routes.rb
Preeschool::Application.routes.draw do

  resources :invoices
  resources :registrations, only: [:new, :edit, :create, :update]

  mount RailsEmailPreview::Engine, at: 'emails'

  namespace :admin do
    resources :messages
    resources :kids
    resources :families do
      get 'leads', action: :leads, on: :collection
    end
    resources :invoices do
      post 'notice', action: :notice, on: :member
      post 'reminder', action: :reminder, on: :member
      post 'alert', action: :alert, on: :member
      post 'mark_as_payed', action: :mark_as_payed, on: :member
      post 'replace', action: :replace, on: :member
      post 'cancel', action: :cancel, on: :member

      get 'check_payments', action: :check_payments, on: :collection
      post 'check_payments', action: :check_payments, on: :collection
    end
    resources :finances
  end

  comfy_route :gallery_admin, path: '/admin'
  comfy_route :cms_admin, path: '/admin'

  comfy_route :blog_admin, path: '/admin'
  comfy_route :blog, path: '/blogg'

  get '/bankid', to: redirect('bankid:///?redirect=http://forskolan-solsidan.se/admin/invoices?from_bankid=true'), as: :bankid

  comfy_route :cms, path: '/', sitemap: false

end

app/models/kid.rb
require 'adroit-age'

# MAXIMUM_INCOME = (@cms_site.snippets.find_by_identifier('maxtaxa').content.to_i rescue 43700)
# DEFAULT_INCOME = MAXIMUM_INCOME
# MAXIMUM_FEE = MAXIMUM_INCOME * 0.03

class Kid < ActiveRecord::Base
  belongs_to :family

  has_paper_trail # https://github.com/airblade/paper_trail

  scope :by_age, -> { order(ssn: :desc) }
  scope :orphan, -> { where("family_id is null") }
  scope :has_family, -> { where("family_id is not null") }
  scope :by_name, -> (name) { where("full_name ilike ?", "%#{name}%")}

  def self.siblings(family_id)
    where(family_id: family_id)
  end
  def siblings
    self.class.siblings(self.family_id).where("id != ?", self.id)
  end

  before_validation :complete_ssn, on: [:create, :update]
  before_validation :ensure_start_date, on: [:create, :update]
  before_validation :ensure_end_date, on: [:create, :update]

  validates_presence_of :full_name, :start_date
  validates_length_of :full_name, minimum: 3

  validates_presence_of :ssn
  with_options allow_blank: true do |v|
    v.validates_length_of :ssn, is: 13  # 20080101-1234
    v.validates_uniqueness_of :ssn
  end

  def self.maximum_income
    site = Comfy::Cms::Site.first
    # ap Comfy::Cms::Site.all
    site.snippets.find_by_identifier('maxtaxa').content.to_i rescue 43700
  end
  def self.default_income
    self.maximum_income
  end
  def self.maximum_fee
    self.maximum_income * 0.03
  end

  # def self.forenames
  #   map(&:forename).to_sentence
  # end

  def names
    full_name.split(" ") rescue nil
  end

  def forename
    names[0] rescue nil
  end

  def forenames
    names[0...-1].join(" ") rescue nil
  end

  def surname
    names[-1] rescue nil
  end

  def date_of_birth
    Date.parse(self.ssn[0,8]) rescue nil
  end

  def age_now
    date_of_birth.find_age
  end
  def age
    age_by_end_of_year
  end
  def age_by_end_of_year
    date_of_birth.find_age_by_end_of_year
  end
  def age_on(date)
    date_of_birth.find_age_on(date)
  end

  def default_end_date
    # Should be July the year of their 6th birthday
    # FIXME: make sure logic is right - should we really
    # use age_by_end_of_year here?
    (date_of_birth + 6.years).change(month: 7, day: 1)
    # self.start_date + 2.years
  end

  def self.active
    # self.where("now() >= :start_date AND now() <= :end_date",
    #   { start_date: :start_date, end_date: :end_date })
      #
      # Client.where(created_at: (Time.now.midnight - 1.day)..Time.now.midnight)
    select{ |kid| kid.active? }
  end
  def self.inactive
    select{ |kid| !kid.active? }
  end

  # default_scope :active

  def active?
    # TODO rewrite to SQL query
    return false if pending?
    Date.today.between?(start_date, end_date)
  end

  def big # TODO add in view
    age >= 4 # Should this maybe not use age_by_end_of_year?
  end

  # Allmän förskola
  def free_15_hour_week
    september_of_3yob = (date_of_birth + 3.years).change(month: 9, day: 1)
    return age >= 3 &&
      Date.today >= september_of_3yob &&
      Date.today.month != 8
  end

  def fee_percent
    return 0.03 if birth_order.nil?
    pc =
      case birth_order
      when 1 then 0.03
      when 2 then 0.02
      when 3 then 0.01
      else 0
      end
    pc = pc * 0.7 if free_15_hour_week
    pc.round(3)
  end

  def relevant_income
    [family.income || Kid::default_income, Kid::maximum_income].min
  end

  def fee
    return 0 unless active?
    return 0 unless family
    kid_fee = fee_percent * relevant_income
    if family.parent_at_home?
      if free_15_hour_week
        kid_fee = 0
      else
        kid_fee = kid_fee * 0.6
      end
    end
    kid_fee.round(2)
  end

  def birth_order
    return nil unless family
    index = family.kids.order(ssn: :desc).active
      .map(&:id)
      .quick_index(self.id)
    index.to_i + 1
  end


  # Kommunbidrag

  def self.subsidy_break_date # July 1st
    Date.today.change(month: 7, day: 1)
  end

  def subsidy_age
    age_on(Kid.subsidy_break_date)
  end

  def subsidy_young?
    subsidy_age <= 3
  end

  def subsidy
    subsidy_young? ? Kid.subsidy_for_younger : Kid.subsidy_for_older
  end

  def self.current_subsidies_total
    Kid.active.sum(&:subsidy)
  end

  def self.subsidy_for_younger
    (@cms_site.snippets.find_by_identifier('bidrag-yngre-barn').content.to_f rescue 10700.42)
  end
  def self.subsidy_for_older
    (@cms_site.snippets.find_by_identifier('bidrag-aeldre-barn').content.to_f rescue 8047.83)
  end

  protected

    def complete_ssn
      # self.ssn = self.ssn.gsub(/\D/) # TODO: strip of all but numbers and "-"
      if self.ssn and self.ssn.is_a?(String) and self.ssn.length == 8
        self.ssn = self.ssn + '-0000'
      end
    end

    def ensure_start_date
      if !self.start_date?
        self.start_date = Date.today
      end
    end

    def ensure_end_date
      if self.start_date and !self.end_date?
        self.end_date = default_end_date
      end
    end

end

app/controllers/admin/kids_controller.rb
class Admin::KidsController < Comfy::Admin::Cms::BaseController

  before_action :build_kid,  :only => [:new, :create]
  before_action :load_kid,   :only => [:show, :edit, :update, :destroy]

  def index
    # TODO: exclude "expired" kids (>3 months since end date)
    # with a button to show all
    @kids = Kid.order(full_name: :asc)
    if params[:order].present?
      @kids = Kid.order(params[:order].to_sym)
    end
    @kids = @kids.includes(:family).references(:family)
      .page(params[:page])
    if params[:name].present?
      @kids = @kids.by_name(params[:name]).order(full_name: :desc)
      redirect_to edit_admin_kid_path(@kids.first) if @kids.count == 1
    end
  end

  def show
    render
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @kid.save!
    flash[:success] = 'Barn skapades'
    redirect_to :action => :edit, :id => @kid
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Kunde ej skapa barn'
    render :action => :new
  end

  def update
    @kid.update_attributes!(kid_params)
    flash[:success] = 'Barn uppdaterades'
    redirect_to :action => :edit, :id => @kid
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Kunde ej uppdatera barn'
    render :action => :edit
  end

  def destroy
    @kid.destroy
    flash[:success] = 'Barn togs bort'
    redirect_to :action => :index
  end

protected

  def build_kid
    first_names = %w(Georg Elfrida Rutger Katrin Gustaf Caroline Vilhelm Sara)
    last_names = %w(Augustenborg Messenius Moberg Almqvist Adlersparre Adlercreutz Månsdotter)
    @random_name = "#{first_names.sample} #{last_names.sample}"
    @random_ssn = "#{(1...3).to_a.sample.years.ago.to_date.to_s.gsub(/\D/, '')}-0405"

    @kid = Kid.new(kid_params)
  end

  def load_kid
    @kid = Kid
      .includes(:family).references(:family)
      .find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = "Inget barn med id #{params[:id]} kunde hittas"
    redirect_to :action => :index
  end

  def kid_params
    params.fetch(:kid, {}).permit(:full_name, :ssn, :start_date, :end_date, :comment, :family_id, :pending)
  end
end

app/views/admin/kids/_form.html.haml
=# form.text_field :father_name, label: "Namn", icon: "user", placeholder: "Johan Sten", label_col: "col-sm-4", control_col: "col-sm-8"
.row
  .col-sm-7
    = form.text_field :full_name, placeholder: @random_name, icon: "user", label_col: "col-sm-3", control_col: "col-sm-9", class: "input-lg"
  .col-sm-4
    = form.text_field :ssn, placeholder: @random_ssn, label_col: "col-sm-4", control_col: "col-sm-8"

.row
  .col-sm-7
    = form.collection_select :family_id, Family.order(:id), :id, :names_as_sentence, {include_blank: "Ingen", label_col: 'col-sm-3', control_col: 'col-sm-9'}
  .col-sm-5
    - if form.object.family_id?
      - family = form.object.family
      = link_to edit_admin_family_path(family) do
        %span.glyphicon.glyphicon-circle-arrow-right
        = family.name
        - if family.parent_at_home?
          %span.label.label.label-success{title: 'Föräldralediga'} FL


%hr
.row
  .col-sm-6
    = form.date_field :start_date, placeholder: 2.days.from_now.to_date.to_s.gsub(/-/,''), icon: "calendar", help: "Fyller du inte i startdatum blir det idag.", label_col: "col-sm-4", control_col: "col-sm-8", class: 'input-lg'

    = form.date_field :end_date, icon: "calendar", help: "Fyller du inte i slutdatum blir det juli det år de fyller 6 år#{form.object.id? ? ' dvs '+l(form.object.default_end_date, format: :long) : ''}.", label_col: "col-sm-4", control_col: "col-sm-8", class: 'input-lg'

  .col-sm-6
    - if form.object.id?
      .form-group.input-lg
        .form-control-static.col-sm-offset-2.col-sm-10.text-muted
          %span.label.label.label-info #{form.object.age} år
          %span.label.label.label-default #{form.object.fee.to_i} kr / mån
          - if form.object.active?
            %span.label.label.label-success Aktiv
          - else
            %span.label.label.label-default Inaktiv
          - if form.object.free_15_hour_week
            %span.label.label.label-warning{title: 'Har just nu rätt till allmän förskola 15 timmar per vecka'} AFSK

        -#.form-control-static.col-sm-offset-2.col-sm-10.text-muted
          = link_to 'Visa email', rails_email_preview.rep_email_path('fee_mailer_preview-reminder', family_id: form.object.family_id), class: 'btn btn-primary'
          = link_to 'Visa PDF', invoice_path(1, format: :pdf, family_id: form.object.family_id), class: 'btn btn-primary'

    = form.form_group :pending, class: "input-lg" do
      = form.check_box :pending, label: "Avvaktar"

= form.text_area :comment, rows: 3

= form.form_group :class => 'form-actions' do
  .col-sm-6
    = form.submit class: 'btn btn-lg btn-primary'
  .col-sm-6.text-right
    - if form.object.id?
      .btn-group
        = link_to admin_kid_path(form.object), method: :delete, data: { confirm: 'Säker?' }, class: 'btn btn-danger' do
          %span.glyphicon.glyphicon-remove
          Ta bort

app/views/admin/kids/_history.haml
-# REMEMBER that this is mirrored in families/_history.haml

%h3 Historik
- if @kid.history.any?
  - @kid.history.reverse.each do |version|
    - if version
      %h4= l(version[:updated_at], format: :long) if version[:updated_at]
      =# raw ap(version.except(:updated_at), plain: true)
      .row
        - version.except(:updated_at).each do |attribute, values|
          .col-md-6.history-event
            .well
              %h5= t("activerecord.attributes.kid.#{attribute}")
              - if values.is_a?(Array)
                %p
                  - if values[1].is_a?(TrueClass)
                    härmed
                    %strong sant
                  - elsif values[1].is_a?(FalseClass)
                    härmed
                    %strong falskt
                  - else
                    ändrades från
                    %em= values[0] || "(inget)"
                    till
                    %strong= values[1] || "(inget)"
- else
  %p Inga ändringar har gjorts.

app/views/admin/kids/edit.html.haml
.page-header
  .row
    .col-sm-8
      %h2
        = @kid.full_name
        - if @kid.is_lead?
          %span.label.label.label-primary{title: 'Intresseanmäld'} Intresse

    .col-sm-4.text-right
      .btn-group
        = link_to edit_admin_kid_path(@kid.id+1), class: 'btn btn-default', title: 'Nästa barn' do
          %span.glyphicon.glyphicon-arrow-down
          Nästa
        = link_to edit_admin_kid_path(@kid.id-1), class: 'btn btn-default', title: 'Förra barn' do
          %span.glyphicon.glyphicon-arrow-up
          Förra

= comfy_form_for [:admin, @kid] do |form|
  = render form

= render partial: 'history'

app/views/admin/kids/index.html.haml
.page-header
  = link_to new_admin_kid_path, class: 'btn btn-lg btn-default pull-right' do
    %span.glyphicon.glyphicon-plus-sign
    Nytt barn

  %h1
    Barn
    - if params[:order].present?
      %small
        Sorterade efter
        = t("activerecord.attributes.kid.#{params[:order]}")

= paginate @kids, theme: 'comfy'

- cache @kids do
  %table.table.table-hover.table-bordered
    %tr
      %th= link_to 'Namn', admin_kids_path(order: :full_name)
      %th
      %th= link_to 'Ålder', admin_kids_path(order: :ssn)
      %th Familj
      %th
      %th= link_to 'Period', admin_kids_path(order: :start_date)
      %th.narrow
      %th.narrow

    - @kids.each do |kid|
      %tr{class: kid.active? ? '' : 'inactive'}
        %td= link_to kid.forename, edit_admin_kid_path(kid)
        %td
          - if kid.free_15_hour_week
            %span.label.label.label-warning{title: 'Har just nu rätt till allmän förskola 15 timmar per vecka'} AFSK
        %td= "#{kid.age} år"
        %td= link_to kid.family.surnames, edit_admin_family_path(kid.family) rescue ""
        %td= kid.birth_order.nil? ? '' : 'Nr '+kid.birth_order.to_s
        %td
          - if kid.start_date
            = l(kid.start_date, format: :month)
            %span.glyphicon.glyphicon-arrow-right.small
            = l(kid.end_date, format: :month)
        %td
          - if kid.pending?
            %span.glyphicon.glyphicon-pause{title: "Avvaktar"}
          - elsif kid.active?
            / %span.glyphicon.glyphicon-ok-sign{title: "Aktiv"}
        %td
          - if kid.comment?
            %span.glyphicon.glyphicon-comment{title: "Kommentar"}

    %tfoot{style:'background-color:#eee'}
      %tr
        %td= "#{Kid.count} st"
        %td
        %td
        %td
        %td
        %td= "#{Kid.has_family.active.count} st aktiva"
        %td
        %td

= paginate @kids, theme: 'comfy'

app/views/admin/kids/new.html.haml
.page-header
  %h2 Nytt barn

= comfy_form_for [:admin, @kid] do |form|
  = render form

app/views/admin/kids/show.html.haml
.page-header
  %h2 Barn
  
= debug @kid